authors: [ eccentric_nz ]
main: me.eccentric_nz.tardissonicblaster.TardisSonicBlasterPlugin
name: TARDISSonicBlaster
description: The blaster used digital technology to create a sonic wave, projected into the form of pulsing squares of blue light, which could cut through thick walls. It also had a reverse function which could replace the removed chunk of material afterwards.
version: ${project.version}
api-version: 1.17
load: POSTWORLD
depend: [ TARDIS ]
website: http://tardisjenkins.duckdns.org:8080/job/TARDISSonicBlaster/
dev-url: https://github.com/eccentricdevotion/TARDISSonicBlaster/
url: http://eccentricdevotion.github.io/TARDIS/
permissions:
  sb.use:
    description: Allow players to use Sonic Blasters.
    default: op
